### PR TITLE
Use Q-encode to wrap too long headers

### LINKED ISSUE #1469: Long filenames in "Content-Disposition: attachment; filename" breaks extension
**- Problem description**
I've been getting several complaints by customers about them receiving mail with attachments which they cannot open because of some malformed file extension.

It turns out the filenames are folded after 76 characters. This SEEMS RFC-compliant.
The extra spacing character is interpreted as a space and, of course, doesn't cause problems when not in the extension.

When sending the same, original, file through Outlook (client or web), GMail or any other hosted service, the file arrives with the complete and untouched extension.

**- Code/Steps to reproduce**
Send an email and include a file with a filename just over 76 characters long.

```
$filename = "WayTooLongFileNameWhichWillCorruptTheFileExtensionAtCharacterSeventySeven.pdf"; // filename is 77 characters
$mailer->AddAttachment($att->file, $filename, $att->encoding, $att->mimeType);
```

**- Debug Output**
```
--b1_6IjFX38R88zg8cQbwrrdGs9XKE4P6sRVpqGdadM00Is
Content-Type: application/pdf; name="WayTooLongFileNameWhichWillCorruptTheFileExtensionAtCharacterSeventySeven.pd f"
Content-Transfer-Encoding: base64
Content-ID: <WayTooLongFileNameWhichWillCorruptTheFileExtensionAtCharacterSeventySeven.pdf>
Content-Disposition: attachment; filename="WayTooLongFileNameWhichWillCorruptTheFileExtensionAtCharacterSeventySeven.pd f"
```

**- Possible solution**
As said, the current implementation SEEMS RFC-compliant. But [RFC 2184 Section 3](https://tools.ietf.org/html/rfc2184#section-3) speaks about Parameter Value Continuation and ways to break too long parameter values into smaller chunks without folding and altering the original values.

> RFC 2184 Section 3
>    ...
>    
>    The obvious solution, then, is to use multiple parameters to contain
>    a single parameter value and to use some kind of distinguished name
>    to indicate when this is being done.  And this obvious solution is
>    exactly what is specified here: The asterisk character ("*") followed
>    by a decimal count is employed to indicate that multiple parameters
>    are being used to encapsulate a single parameter value.  The count
>    starts at 0 and increments by 1 for each subsequent section of the
>    parameter value.  Decimal values are used and neither leading zeroes
>    nor gaps in the sequence are allowed.
> 
>    The original parameter value is recovered by concatenating the
>    various sections of the parameter, in order.  For example, the
>    content-type field
> 
>      Content-Type: message/external-body; access-type=URL;
>       URL*0="ftp://";
>       URL*1="cs.utk.edu/pub/moore/bulk-mailer/bulk-mailer.tar"
> 
>    is semantically identical to
> 
>      Content-Type: message/external-body; access-type=URL;
>       URL="ftp://cs.utk.edu/pub/moore/bulk-mailer/bulk-mailer.tar"

Shortening filenames is not an option because:
- clients include specific indentifiers into the filename which can differ in length
- regular email clients are able to send files with names exceeding 76 characters in length without folding/altering

**- System-info**
PHPMailer 6.0.5 (Composer)
PHP 7.1
CentOS 6.9/7.4

Can you look into this?
Thank you!

### LINKED ISSUE #1525: Long header folding adds additional spaces
If sending a long header without spaces, header folding is incorrectly.

Headers should fold with a CRLF, but after folding the CRLF is replaced with a LF and a space is introduced: 

    $encoded = trim(chunk_split($str, static::STD_LINE_LENGTH, static::$LE));

This is correct; but 

    $encoded = str_replace(static::$LE, "\n", trim($encoded));
    $encoded = preg_replace('/^(.*)$/m', ' \\1', $encoded);

corrupts the folding; order should be different.

### PR DESCRIPTION
**Pull request by caugner**
Fixes #1469.
Fixes #1525.

### CODE REVIEW

**Comment by caugner** [comment]
There is [one test case](https://travis-ci.org/PHPMailer/PHPMailer/jobs/588482898#L331) that expects the previous behaviour:

grafik

**Comment by caugner** [comment]
As for the test case, this is fixed in 8701f3b.

Regarding the charset selection, isn't this a separate issue of `PHPMailer::encodeHeader`? Currently it always Q-encodes any value using the `PHPMailer::$CharSet`, whereas it could be more clever and prefer less expensive charsets such as `us-ascii` or `7bit` if applicable.

**Comment by Synchro** [comment]
Yes, exactly that (though 7bit is a CTE, not a charset).

File: src/PHPMailer.php [hunk 1]
```diff
@@ -3163,15 +3163,6 @@ public function encodeHeader($str, $position = 'text')
             $encoded = $this->wrapText($encoded, $maxlen, true);
             $encoded = str_replace('=' . static::$LE, "\n", trim($encoded));
             $encoded = preg_replace('/^(.*)$/m', ' =?' . $this->CharSet . "?$encoding?\\1?=", $encoded);
```
Comment (caugner) [inline src/PHPMailer.php]: @Synchro Can we simply use `us-ascii` here instead of `$this->CharSet` if `!$this->has8bitChars($encoded)`?

Comment (Synchro) [reply src/PHPMailer.php]: I think so - the only hole would be if it uses some unusual 7-bit charset that was not ascii compatible.

Comment (Synchro) [reply src/PHPMailer.php]: It would be cool to add a test to create headers in both formats.

**Comment by caugner** [comment]
> UTF-8 is excessive for something that doesn't contain 8-bit chars

Can you illustrate why UTF-8 is more excessive in this case:

```
=?UTF-8?Q?eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee?=
  =?UTF-8?Q?eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee?=

vs.

=?us-ascii?Q?eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee?=
  =?us-ascii?Q?eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee?=
```

Isn't `us-ascii` a subset of `UTF-8`?

**Comment by Synchro** [comment]
While the content is indeed identical and compatible, marking it as UTF-8 requires firing up a complete unicode engine to decode it on the receiver, which is unnecessary overhead if we know in advance it's plain ASCII. In PHP for example, we would not be able to decode it easily if we didn't have the `mbstring` extension enabled, whereas it would present no problems in us-ascii.

 It's like putting literal IPs first in SPF records; it's not a requirement, but it makes life easier for receivers.

File: src/PHPMailer.php (hunk 1 above)
Comment (caugner) [reply src/PHPMailer.php]: > I think so - the only hole would be if it uses some unusual 7-bit charset that was not ascii compatible.

Do we need to handle this case somehow, if we can handle it all?

> It would be cool to add a test to create headers in both formats.

Added in 9e1f8f1 .

Comment (Synchro) [reply src/PHPMailer.php]: Great stuff, thanks. Anyone that's using a non-ascii-compatible charset probably has bigger problems, so I don't think we need to worry about it...

**Comment by caugner** [comment]
Unfortunately, CI has [some unrelated problems](https://travis-ci.org/PHPMailer/PHPMailer/jobs/588540025#L250):

grafik

File: src/PHPMailer.php [hunk 2]
```diff
@@ -3154,24 +3155,20 @@ public function encodeHeader($str, $position = 'text')
                 $encoded = trim(chunk_split($encoded, $maxlen, "\n"));
             }
             $encoded = preg_replace('/^(.*)$/m', ' =?' . $this->CharSet . "?$encoding?\\1?=", $encoded);
-        } elseif ($matchcount > 0) {
+        } elseif ($matchcount > 0 || strlen($str) > $maxlen) {
             //1 or more chars need encoding, use Q-encode
```
Comment (caugner) [inline src/PHPMailer.php]: TODO Update comment

**Comment by caugner** [comment]
> I wonder if this will fix #1525 as well?!

I think so.

Maybe you could have a ~~second~~ third look? I have now refactored my PR as follows:

* Aligned commit messages with the usual style in this repository (consistency).
* Separated encoding selection from encoding (readability, separation of concerns).
* Applied charset selection to B-encoding as well (consistency).

File: src/PHPMailer.php [hunk 3]
```diff
@@ -3134,47 +3135,57 @@ public function encodeHeader($str, $position = 'text')
         //corrupt messages with headers longer than 65 chars. See #818
         $lengthsub = 'mail' == $this->Mailer ? 13 : 0;
         $maxlen = static::STD_LINE_LENGTH - $lengthsub;
```
Comment (Synchro) [inline src/PHPMailer.php]: This assumption may need looking at too - This came up in #1525 - it's OK to have a line longer than 76 chars if it contains no embedded spaces that it can be folded on - we should only force RFC2047 encoding if a line is over 998.
I think we need another check to see if the line has no 8-bit chars and contains an unspaced sequence longer than `MAX_LINE_LENGTH` chars (I guess something like `/\w{MAX_LINE_LENGTH,}/`), then we should force Q-encoding, which will wrap the whole header to `STD_LINE_LENGTH`. This isn't absolutely needed as there's no significant harm in wrapping earlier other than a mild increase in size, but it would be a "nice to have".

There's another bug related to this in #36, in that the header label is not taken into account in the length - that's not been critical since it only becomes a problem at the 998 char limit, but we should perhaps allow for that by wrapping a bit before 998, in a similar way that we try to avoid folding bugs in `mail()`.

So I think here we might rename `$maxlen` as `$foldlen` and set `$maxlen` to `static::MAX_LINE_LENGTH - $lengthsub`, then use them in appropriate places. This will affect test outcomes.

Everything else in here is great!

Comment (caugner) [reply src/PHPMailer.php]: > This assumption may need looking at too

Actually, I just extracted this from the two branches (B and Q) for the sake of deduplication. Or did I miss anything?

> There's another bug related to this in #36, in that the header label is not taken into account in the length 

You're right that #36 (which I [did notice](https://github.com/PHPMailer/PHPMailer/issues/1469#issuecomment-534108894)) could be fixed as part of this PR, but in general I would opt against also fixing that one in this PR (which already does more than just *Us[ing] Q-encode to wrap too long headers*).

I'm not sure fixing #36 is as trivial since it would require touching several places where the encoded header *value* is just appended to the header name (e.g. `Content-Type`, `Content-Disposition`, etc.), like here:

https://github.com/PHPMailer/PHPMailer/blob/3c1c6e03603364ab9ba774b062ca4a5270b90adb/src/PHPMailer.php#L2941-L2954

Or am I missing anything?

Comment (Synchro) [reply src/PHPMailer.php]: Indeed – we don't need to *fix* #36 in this PR, but a fudge here will certainly help. If we force Q+folding at say `MAX_LINE_LENGTH - 50` (which isn't quite RFC, but is harmless), to have a problem related to it you would need to have both a) a header label longer than 48 chars and b) a header value > 998 chars with no spaces, which is a very unlikely combo, sufficiently so that we could probably forget about #36.

Comment (Synchro) [reply src/PHPMailer.php]: I'm having second thoughts about my last comment. We don't need to worry about lines between 76 and 998 chars long in an SMTP context, but in PHP and sending via `mail()`, we do, because of the bug noted mentioned the source, and on here in #818, where lines longer than 65 chars cause issues. Because of that we may as well not bother allowing long lines to exist and leave the encoding behaviour as it stands in your PR.

Comment (caugner) [reply src/PHPMailer.php]: I committed an intermediate state (c4b7f6a) where I distinguished `$foldlen` and `$maxlen`, but I reverted this to f71240d, deduplicating the `$maxlen` calculation as originally intended (and hopefully making it clearer).

**Comment by Synchro** [comment]
This was a great bit of work, solving several long-standing bugs that I'd been procrastinating about! Thank you very much for all your effort. This set of changes and other things that have happened lately mean that I will release this as PHPMailer 6.1 soon. Would you be interested in joining the PHPMailer org?

**Comment by caugner** [comment]
@Synchro Thank you for your reviews and the merge. And sure, feel free to add me to the org. I might like to tackle the header name vs. header value line length limitation at some point.
